<?php

interface PersonInterface {
    public function getInfo();
}

abstract class Person implements PersonInterface {
    protected $name;
    protected $age;

    public function __construct($name, $age) {
        $this->name = $name;
        $this->age = $age;
    }

    public function getInfo() {
        // TODO: Implement getInfo() method.
        return "Name: {$this->name} <br> Age: {$this->age} <br>";
    }
}

class Student extends Person {
    private $major;

    public function __construct($name, $age, $major) {
        parent::__construct($name, $age);
        $this->major = $major;
    }

    public function getInfo() {
        return parent::getInfo() . "Major: {$this->major}"; // TODO: Change the autogenerated stub
    }

}

$student = new Student('Ivan', 30, "Programming");
echo $student->getInfo();